version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=magic
      - POSTGRES_DB=learn-jpa
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/learn-jpa -user=root -password=magic -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/migrations/:/flyway/sql:ro
    depends_on:
      - postgres
  oracle:
    image: webdizz/oracle-xe-11g-sa:latest
    container_name: oracle
    ports:
      - "15080:8080"
      - "1521:1521"
    environment:
      - processes=200
      - DATABASES=sample
#     Connect as system user and explore HR schema
#     - username: system
#     - password: oracle
#    volumes:
#      - .oracle_data:/u01/app/oracle
